[build]
  # Don’t let Netlify try to build Flutter (since it doesn’t have Flutter SDK by default)
  command = ""
  publish = "build/web"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
